### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by kenzopanel** [janvernieuwe/jikan-jikanPHP#4]
$ composer require jikan/jikan-php
./composer.json has been updated
Loading composer repositories with package information                                                                                                                   Updating dependencies     
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jms/serializer[1.13.0, ..., 1.14.1] require php ^5.5|^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - jms/serializer[2.0.0, ..., 2.3.0] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires jms/serializer ^1.13|^2.0 satisfiable by jms/serializer[1.13.0, 1.14.0, 1.14.1, 2.0.0, ..., 2.3.0]. 

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by janvernieuwe** [comment]
Hi @kenzopanel,

I'll take a look for upgrading to php8 when I find the time.
Meanwhile you're always welcome to make a pull request with the updated libraries!

**Comment by janvernieuwe** [comment]
See v4 branch
